packages:
  - "apps/*"
  - "packages/**"
  - "tooling/**"
  - "config/**"

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true

catalog:
  "@base-ui/react": "*"
  "@hookform/resolvers": "*"
  "@makerkit/data-loader-supabase-core": "*"
  "@makerkit/data-loader-supabase-nextjs": "*"
  "@manypkg/cli": "*"
  "@marsidev/react-turnstile": "*"
  "@next/bundle-analyzer": "*"
  "@playwright/test": "*"
  "@supabase/ssr": "*"
  "@supabase/supabase-js": "*"
  "@tailwindcss/postcss": "*"
  "@tanstack/react-query": "*"
  "@tanstack/react-table": "*"
  "@turbo/gen": "*"
  "@types/mdx": "*"
  "@types/node": "*"
  "@types/react": "*"
  "@types/react-dom": "*"
  "autoprefixer": "*"
  "babel-plugin-react-compiler": "*"
  "class-variance-authority": "*"
  "clsx": "*"
  "cmdk": "*"
  "cross-env": "*"
  "date-fns": "*"
  "dotenv-cli": "*"
  "embla-carousel-react": "*"
  "input-otp": "*"
  "lucide-react": "*"
  "nanoid": "*"
  "next": "*"
  "next-intl": "*"
  "next-safe-action": "*"
  "next-sitemap": "*"
  "next-themes": "*"
  "node-html-parser": "*"
  "oxfmt": "*"
  "oxlint": "*"
  "pino": "*"
  "pino-pretty": "*"
  "react": "*"
  "react-day-picker": "*"
  "react-dom": "*"
  "react-dropzone": "*"
  "react-hook-form": "*"
  "react-resizable-panels": "*"
  "react-top-loading-bar": "*"
  "recharts": "*"
  "server-only": "*"
  "shadcn": "*"
  "sonner": "*"
  "supabase": "*"
  "tailwind-merge": "*"
  "tailwindcss": "*"
  "tailwindcss-animate": "*"
  "turbo": "*"
  "typescript": "*"
  "vaul": "*"
  "vitest": "*"
  "zod": "*"
