
'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { TraceabilityShell, EmptyWorkspace } from '../../_components/TraceabilityShell';
import styles from '../../_components/traceability.module.css';
import { useProducerWorkspace } from '../../_lib/use-producer-workspace';
import { batchCode, csvEscape, downloadText, formatDate, productName, stageName } from '../../_lib/producer-utils';
export default function RegistosPage(){const {store,loading}=useProducerWorkspace();const [q,setQ]=useState('');const [product,setProduct]=useState('');const [stage,setStage]=useState('');const rows=useMemo(()=>{if(!store)return[];return [...store.records].sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).filter(r=>(!product||r.productId===product)&&(!stage||r.stageId===stage)&&(!q||`${productName(store,r.productId)} ${batchCode(store,r.batchId)} ${stageName(store,r.stageId)}`.toLowerCase().includes(q.toLowerCase())))},[store,q,product,stage]);if(loading)return <TraceabilityShell eyebrow="Produção" title="Registos"><div className={styles.cardPad}>A carregar…</div></TraceabilityShell>;if(!store?.completed)return <TraceabilityShell eyebrow="Produção" title="Registos"><EmptyWorkspace/></TraceabilityShell>;function exp(){const head='Data;Produto;Lote;Etapa;Unidades;Dados';const lines=rows.map(r=>[r.createdAt,productName(store,r.productId),batchCode(store,r.batchId),stageName(store,r.stageId),r.productionUnitIds.length,JSON.stringify(r.data)].map(csvEscape).join(';'));downloadText(`registos-${store.business.name}.csv`,[head,...lines].join('\n'))}return <TraceabilityShell eyebrow="Produção · Registos" title="Registos de produção" description="Histórico pesquisável dos dados de rastreabilidade." actions={<><button className={styles.secondary} onClick={exp}>Exportar CSV</button><Link className={styles.primary} href="/dashboard/producao/inserir-dados">+ Novo registo</Link></>}><section className={styles.card}><div className={styles.toolbar}><input className={styles.search} placeholder="Pesquisar registo…" value={q} onChange={e=>setQ(e.target.value)}/><div className={styles.toolbarGroup}><select className={styles.select} style={{width:180}} value={product} onChange={e=>setProduct(e.target.value)}><option value="">Todos os produtos</option>{store.products.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><select className={styles.select} style={{width:180}} value={stage} onChange={e=>setStage(e.target.value)}><option value="">Todas as etapas</option>{store.stages.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Data</th><th>Produto</th><th>Lote</th><th>Etapa</th><th>Origem</th><th>Dados</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className={styles.nowrap}>{formatDate(r.createdAt,true)}</td><td><strong>{productName(store,r.productId)}</strong></td><td>{batchCode(store,r.batchId)}</td><td><span className={`${styles.badge} ${styles.badgeGood}`}>{stageName(store,r.stageId)}</span></td><td>{r.productionUnitIds.length} unidade(s)</td><td className={styles.muted}>{Object.entries(r.data).slice(0,2).map(([k,v])=>`${k}: ${String(v)}`).join(' · ')||'—'}</td></tr>)}{!rows.length?<tr><td colSpan={6}>Sem registos para os filtros selecionados.</td></tr>:null}</tbody></table></div></section></TraceabilityShell>}
